# Generated by Django 6.0.5 on 2026-05-27 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trade",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "hora",
                    models.TimeField(
                        auto_now_add=True, verbose_name="Hora da Operação"
                    ),
                ),
                (
                    "ativo",
                    models.CharField(max_length=10, verbose_name="Ativo (Ex: PETR4)"),
                ),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Preço"
                    ),
                ),
                ("qtd", models.IntegerField(verbose_name="Quantidade")),
                (
                    "sinal",
                    models.CharField(
                        choices=[("C", "Compra"), ("V", "Venda")],
                        max_length=1,
                        verbose_name="Sinal",
                    ),
                ),
            ],
        ),
    ]
