# Generated by Django 6.0.5 on 2026-05-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ative_rest", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coin",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "symbol",
                    models.CharField(
                        max_length=20, verbose_name="Símbolo da Moeda (Ex: BTCUSDT)"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, verbose_name="Nome da Moeda (Ex: Bitcoin)"
                    ),
                ),
            ],
        ),
    ]
